export { default as Header } from './section/Header'
export { default as Hero } from './section/Hero/Hero'
export { default as About } from './section/About/About'
export { default as Skills } from './section/Skills/Skills'
export { default as Projects } from './section/Projects/Projects'
export { default as Footer } from './section/Footer'
